name: darty_lisp
description: A starting point for Dart libraries or applications.
version: 0.1.1
homepage: https://github.com/walleXD/darty_lisp
author: Walee Ahmed <dev@walee.me>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  path: ^1.4.1
  args: "^1.5.1"

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
